/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinica;

import forms.especilidades.FrmEspecialidades;
import forms.obrasocial.FrmObraSocial;
import forms.pacientes.FrmPacientes;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import miselaneos.Fecha;
import miselaneos.GUI;
import miselaneos.Iconos;
import miselaneos.imagenes;

public class FrmSistema extends javax.swing.JFrame {

    public static Iconos iconos = new Iconos(); //Declaro public y static para poder acceder luego desde cualquier lugar del proyecto en cualquier objeto
    public static imagenes imgs = new imagenes();
    public static Fecha Fe = new Fecha(); //Misma situacion que Iconos    
    private GUI gui;

    /**
     * Creates new form FrmSistema
     */
    public FrmSistema() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        gui = new GUI();
    }

    private void loadObraSocial() {
        gui.loadObraSocial(FrmObraSocial.id, true);
    }

    private void loadPacientes() {
        gui.loadPacientes(FrmPacientes.id, true);
    }

    private void loadEspecialidades() {
        gui.loadEspecialidades(FrmEspecialidades.id, true);
    }

    /**
     * Metodo para salir del sistema
     */
    private void salirSistema() {
        if (JOptionPane.showConfirmDialog(null, "Desea Salir del Sistema por Completo.", "ATENCIÓN!!!", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDeskTopSis = new miselaneos.JDeskTopSis();
        btnNota = new javax.swing.JButton();
        jToolBarButtons = new javax.swing.JToolBar();
        btnObraSocial = new botones.BtnObraSocial();
        btnClient = new botones.BtnClient();
        btnExit = new botones.BtnExit();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuArchivos = new javax.swing.JMenu();
        jMenuIObraSocial = new javax.swing.JMenuItem();
        jMenuPacientes = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Clinica");
        setIconImage(iconos.getSys(16).getImage());

        jDeskTopSis.setPreferredSize(new java.awt.Dimension(1024, 800));

        btnNota.setText("Nota");
        btnNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotaActionPerformed(evt);
            }
        });
        jDeskTopSis.add(btnNota);
        btnNota.setBounds(10, 10, 68, 25);

        getContentPane().add(jDeskTopSis, java.awt.BorderLayout.CENTER);

        jToolBarButtons.setRollover(true);

        btnObraSocial.setText("");
        btnObraSocial.setFocusable(false);
        btnObraSocial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnObraSocial.setMaximumSize(new java.awt.Dimension(70, 40));
        btnObraSocial.setMinimumSize(new java.awt.Dimension(70, 40));
        btnObraSocial.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnObraSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObraSocialActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnObraSocial);

        btnClient.setText("");
        btnClient.setFocusable(false);
        btnClient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClient.setMaximumSize(new java.awt.Dimension(70, 40));
        btnClient.setMinimumSize(new java.awt.Dimension(70, 40));
        btnClient.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnClient);

        btnExit.setText("");
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnExit);

        getContentPane().add(jToolBarButtons, java.awt.BorderLayout.NORTH);

        jMenuArchivos.setText("Archivo");
        jMenuArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArchivosActionPerformed(evt);
            }
        });

        jMenuIObraSocial.setIcon(iconos.getObraSocial(32)
        );
        jMenuIObraSocial.setText("Obra Social");
        jMenuIObraSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIObraSocialActionPerformed(evt);
            }
        });
        jMenuArchivos.add(jMenuIObraSocial);

        jMenuPacientes.setIcon(iconos.getClient(32));
        jMenuPacientes.setText("Pacientes");
        jMenuPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPacientesActionPerformed(evt);
            }
        });
        jMenuArchivos.add(jMenuPacientes);

        jMenuItem1.setIcon(iconos.getEspecialidades(32)
        );
        jMenuItem1.setText("Especialidades");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuArchivos.add(jMenuItem1);

        jMenuBar.add(jMenuArchivos);

        jMenuSalir.setText("Salir");

        jMenuItem3.setIcon(iconos.getExit(16));
        jMenuItem3.setText("Salir Del Sistema");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuSalir.add(jMenuItem3);

        jMenuBar.add(jMenuSalir);

        setJMenuBar(jMenuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        salirSistema();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        salirSistema();
    }//GEN-LAST:event_btnExitActionPerformed

    private void jMenuIObraSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIObraSocialActionPerformed
        loadObraSocial();
    }//GEN-LAST:event_jMenuIObraSocialActionPerformed

    private void jMenuArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArchivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuArchivosActionPerformed

    private void btnObraSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObraSocialActionPerformed
        loadObraSocial();
    }//GEN-LAST:event_btnObraSocialActionPerformed

    private void jMenuPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPacientesActionPerformed
        loadPacientes();
    }//GEN-LAST:event_jMenuPacientesActionPerformed

    private void btnClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientActionPerformed
        loadPacientes();
    }//GEN-LAST:event_btnClientActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        loadEspecialidades();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotaActionPerformed
        String msj = "Modulo CRUD de Especialidades(0 puntos) trabaja con la tabla de obra social\n"
                + "Modulo CRUD de Obra Social(3 puntos)\n"
                + "Modulo CRUD de Pacientes(4 puntos)\n"
                + "Nota : 8 puntos";

        JOptionPane.showMessageDialog(btnNota, msj, "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnNotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private botones.BtnClient btnClient;
    private botones.BtnExit btnExit;
    private javax.swing.JButton btnNota;
    private botones.BtnObraSocial btnObraSocial;
    public static miselaneos.JDeskTopSis jDeskTopSis;
    private javax.swing.JMenu jMenuArchivos;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuIObraSocial;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuPacientes;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JToolBar jToolBarButtons;
    // End of variables declaration//GEN-END:variables

}
