    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms.obrasocial;

import datos.ObraSocial;
import entidades.obraSocial;
import java.util.ArrayList;
import java.util.TreeMap;
import javax.swing.DefaultComboBoxModel;


public class pnlComboObraSociales extends javax.swing.JPanel {
    private TreeMap<Integer, obraSocial> listobraSocial;
    private DefaultComboBoxModel modeloCombo;
    /**
     * Creates new form pnlComboObraSociales
     */
    public pnlComboObraSociales() {
        initComponents();
        _loadObraSocial();
    }
    
    private void _loadObraSocial(){
        ArrayList<obraSocial> list = new ArrayList<obraSocial>();
        ObraSocial cnx = new ObraSocial();
        if(cnx.isOkConexion()){
            list = cnx.listObraSocial("SELECT * FROM " + cnx.TABLA + " ORDER BY descripcion");
            cnx.isCloseConexion();
        }
        listobraSocial = new TreeMap<Integer, obraSocial>();
        modeloCombo = new DefaultComboBoxModel<String>();
        this.jComboBox.setModel(modeloCombo);
        
        for(int index=0;index<list.size();index++){
            obraSocial obraSocial = list.get(index);
            modeloCombo.addElement(obraSocial.getObrasocial().trim());
            listobraSocial.put(index, obraSocial);
        }
    }
    public obraSocial _getObraSocialSelected(){
        return listobraSocial.get(jComboBox.getSelectedIndex());
    }
    
    public void _setObraSocialSelected(int idobrasocial){
        int indexSelectedCombo = -1;
        for(int index=0;index<listobraSocial.size();index++){
            obraSocial obraSocial = listobraSocial.get(index);
            if(obraSocial.getId()==idobrasocial){
                indexSelectedCombo = index;
            }
        }
        jComboBox.setSelectedIndex(indexSelectedCombo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblObraSocial1 = new etiquetas.LblObraSocial();
        jComboBox = new javax.swing.JComboBox<>();
        btnUpdate = new botones.BtnUpdate();

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnUpdate.setText("");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblObraSocial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblObraSocial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        _loadObraSocial();
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private botones.BtnUpdate btnUpdate;
    private javax.swing.JComboBox<String> jComboBox;
    private etiquetas.LblObraSocial lblObraSocial1;
    // End of variables declaration//GEN-END:variables
}
